version: '3.4'

services:
  signalbotalive:
    image: signalbotalive
    container_name: signalbotalive
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:


    ports:
      - 5432:3000
