name: Update Docker Hub Description
on:
  push:
    branches: [ main ]
    paths:
      - README.md
      - .github/workflows/description_update.yml
  pull_request:
    branches: [ main ]
    paths:
      - README.md
      - .github/workflows/description_update.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: petersem/signalbot
        short-description: ${{ github.event.repository.description }}
